### ISSUE TITLE
Consistent curly use in `where` syntax?

### ISSUE THREAD

**Issue by c42f** [JuliaComputing/Deprecations.jl#1]
For my packages, I've been using the convention that the `where` keyword is always accompanied by curlies.  Thus:

```julia
# yes
function foo(x::T) where {T<:Int}
end
# no
function foo(x::T) where T<:Int
end
```

To get a second opinion I looked in `Base` with some rough grepping.  The results are, unfortunately, inconclusive, but slightly prefer including the curlies:

```bash
# Without curiles
~/src/julia-git/base$ grep '\<where\> *[^ {][^`,}]*.*$' $(find -name \*.jl) | wc -l
942 # a little inflated by false positives due to docs

# With curlies
~/src/julia-git/base$ grep '\<where\> *{[^ {][^`,}]*}.*$' $(find -name \*.jl) | wc -l
1123
```

Should Deprecations be updated to always produce curlies for consistency? This might be a contentious issue, but I thought I'd ask :-)

**Comment by c42f** [comment]
Ack.  I can't write a simple example properly, it seems! I updated the description to fix the example.

**Comment by tkoolen** [comment]
Ref https://github.com/JuliaLang/julia/pull/23245#discussion_r132912843 for one-liners, but I'm also a proponent of always using curly braces.

**Comment by Keno** [comment]
This is happening by design. For single type parameters in long form syntax, curlies are omitted. It's easy to change either way, so this is a policy decision.

**Comment by ararslan** [comment]
+1 for curly in short form and no curly in long form, i.e. how FemtoCleaner currently does it.

**Comment by Keno** [comment]
It does still put curlies in long form for multi arg forms, i.e.
```
function f{S,T}(x::Tuple{S,T})
end
```
becomes
```
function f(x::Tuple{S,T}) where {S,T}
end
```

**Comment by ararslan** [comment]
Right, +1 for that too

**Comment by Keno** [comment]
Survey says a bunch of people like the current behavior. Once we have more fully-featured formatting capabilities in the julia ecosystem, there could be a general settings format which FemtoCleaner could respect. Until then, I'll leave this as is.

**Comment by GlenHertz** [comment]
Writing `where {X, Y, Z}` without squiggly brackets isn't obvious.  Having two different syntaxes for the same thing is confusing plus the parsing is already complicated. Consistency for new users would help readability by always using squiggly brackets for type parameters. In the end I'll probably use whatever is the most popular but I don't want to be reading or writing `where X where Y where Z` (or is it `where Z where Y where X`?).

**Comment by tkoolen** [comment]
That's not the issue here. This is only about standard (non-one-liner) functions that have a single type parameter.

**Comment by c42f** [comment]
It seems that teams using opinionated but readable automatic formatting just get used to it and it removes one point of friction. So in some ways I wish the language itself would have just one way to write this, as `{T}` seems a small syntax burden over `T`.

But in any case, thanks for all your thoughts, the current behavior is quite readable.
