### ISSUE TITLE
UTF8String is not changed if it's a type field

### ISSUE THREAD

**Issue by ararslan** [JuliaComputing/Deprecations.jl#17]
Consider the following diff, generated by Deprecations current master (as of this writing):
```diff
-immutable PkgMeta
+struct PkgMeta
     name::Compat.UTF8String
     url::Compat.UTF8String
     versions::Vector{PkgMetaVersion}
@@ -93,7 +93,7 @@ function get_pkg(pkg_name::AbstractString;
         ver_path = joinpath(vers_path, dir)
         sha = strip(readstring(joinpath(ver_path,"sha1")))
         req_path = joinpath(ver_path,"requires")
-        reqs = Compat.UTF8String[]
+        reqs = String[]
```
Notice that in the type definition, the field `name` is declared as `::Compat.UTF8String`, but this is left untouched. But at the bottom of the diff, when `Compat.UTF8String` is used in a typed empty array literal, it gets properly changed to `String`.

**Comment by KristofferC** [comment]
```
julia> str = """
       struct PkgMeta
            name::Compat.UTF8String
            url::Compat.UTF8String
       end
       """;

julia> print(Deprecations.edit_text(str)[2])
struct PkgMeta
     name::String
     url::String
end
```

Could you link to a more complete example?

**Comment by KristofferC** [comment]
Ok, I repod on https://raw.githubusercontent.com/JuliaPackaging/MetadataTools.jl/8914643b9d0ade10de1d93e5e5291048a5bd2c0c/src/MetadataTools.jl

**Comment by KristofferC** [comment]
See https://github.com/KristofferC/BotTestingRepo/pull/94/files#diff-29d87b5a152286c63c17afe8caa8aa42L24 too see that it is working.

Please comment if I have misunderstood something.

**Comment by ararslan** [comment]
> Is that what you are doing?

No, I was using `edit_file`.

**Comment by KristofferC** [comment]
`edit_file` also runs the passes only once. Perhaps that should be changed, what do you think @Keno?

**Comment by Keno** [comment]
Maybe? We use `edit_text` at least for testing the one-pass result. Seems weird if `edit_file` would automatically iterate.

**Comment by ararslan** [comment]
Could a convenience function be provided that would automatically iterate then?

**Comment by KristofferC** [comment]
This package could be considered a pure backend and everything for users should be added to FemtoCleaner?

**Comment by KristofferC** [comment]
For local runs, see https://github.com/JuliaComputing/FemtoCleaner.jl#running-femtocleaner-locally
