### ISSUE TITLE
Space out ternaries

### ISSUE THREAD

**Issue by ararslan** [JuliaComputing/Deprecations.jl#4]
Omitting a space between the condition and the question mark in ternaries is deprecated as of https://github.com/JuliaLang/julia/pull/22523 (0.7.0-DEV.797). Further, as of https://github.com/JuliaLang/julia/pull/22712 (0.7.0-DEV.1004), omitting spaces on either side of `?` and `:` is deprecated in ternaries. It would be great if this was something that could be recognized and handled appropriately.

**Comment by Keno** [comment]
Fixed in ef7774974e4b9cb7b69f0ff1efa3d6c371433e45
