### ISSUE TITLE
digits keyword argument added to round even when not appropriate

### ISSUE THREAD

**Issue by jgreener64** [JuliaComputing/Deprecations.jl#50]
`round(5.55, 2)` is changed to `round(5.55, digits=2)`, which is correct.

But `round(Int, 5.55)` is also changed to `round(Int, digits=5.55)`, which is not correct.

Hope this helps!

**Comment by fredrikekre** [comment]
f52839a8ad111639599cd48223ca4129826bb5a9 should fix or at least help with simple cases of this.

**Comment by Keno** [comment]
Yes, that should be fixed with that. If you find additional cases (in real code - it's trivial to intentionally defy the heuristics ;) ), please file additional issues.
