### ISSUE TITLE
Global const's seem to be getting removed

### ISSUE THREAD

**Issue by oxinabox** [JuliaComputing/Deprecations.jl#60]
See https://github.com/JuliaText/NameToGender.jl/pull/4/commits/828c066b2a253940dce16bcaa2bdae04348552e7

I had a constant at top-level within my module and Femtocleaner suggested removing it.

Probably related to 
https://github.com/JuliaComputing/Deprecations.jl/commit/5f7c6ddf6291b3288ae8ee9b0b9d3336040756d5
for
https://github.com/JuliaComputing/FemtoCleaner.jl/issues/91

**Comment by Keno** [comment]
Argh, that didn't quite work yet, e.g. in https://github.com/auxetic/Jumos.jl/pull/1

**Comment by Keno** [comment]
Sigh, not quite yet: https://github.com/ViralBShah/SpecFun.jl/pull/4/files#diff-e8179162074030bcd5eb576c831b7974R16
