### ISSUE TITLE
`warn("foo")` -> `@warn("foo")` etc

### ISSUE THREAD

**Issue by oxinabox** [JuliaComputing/Deprecations.jl#63]
It would be good to catch the low-hanging fruit on fixing for the logging changes.
Just getting the single argument forms of `info`, and `warn`
would presumably catch 90% of all uses.

Slack-dump for context:

> Lyndon White [6:35 PM]
> Does Femto cleaner not do `warn(foo)` --> `@warn(foo)` ?
> 
> Fredrik Ekre [6:36 PM]
> No
> 
> Lyndon White [6:36 PM]
> Should I open an issue on Deprecations.jl?
> 
> Fredrik Ekre [6:37 PM]
> I am not sure the transformation is always possible though
> 
> Lyndon White [6:38 PM]
> You are probably right, (though idk why) that issue is listed as a breaking change so the deprecation mustn't always work
> 
> Fredrik Ekre [6:39 PM]
> `warn` takes several arguments for example
> 
> Lyndon White [6:39 PM]
> It might still be better to have Femtocleaner fix it, since presumably 90% of the time it does work?
> Maybe making it fix it in the simplest case
> 
> Fredrik Ekre [6:39 PM]
> Yea
> `warn("foo")` -> `@warn("foo")` for example

**Comment by KristofferC** [comment]
This is also included in the list at https://github.com/JuliaComputing/Deprecations.jl/issues/20
