### ISSUE TITLE
Nullable{T} -> Union{T, Nothing}

### ISSUE THREAD

**Issue by oxinabox** [JuliaComputing/Deprecations.jl#67]
I am just writing this down, I think it is maybe not a good use of anyones time to implement it.
But I want it down for my thought process.

For all of the below, assume `T != Void` (for `T=Void` it is likely better to fix by hand)

 - `Nulltable{T}` --> `Union{Nothing, T}`
 - `get(x)`  with `x::Nullable` (knowing type required) --> `x`
     - Not completely safe because someone could be relying on the exception that `get(null)` throws), but generally useful
 - `isnull(x)`  --> `x==nothing`

**Comment by Keno** [comment]
This is pretty much impossible, since the semantics are not identical. This is one of the things you're gonna have to do manually.
